// <auto-generated />
using ASP_Restaurant.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_Restaurant.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP_Restaurant.Models.MenuName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("menuNames");
                });

            modelBuilder.Entity("ASP_Restaurant.Models.MenuNamePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuNameId")
                        .HasColumnType("int");

                    b.Property<int>("MenuPositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuNameId");

                    b.HasIndex("MenuPositionId");

                    b.ToTable("menuNamePositions");
                });

            modelBuilder.Entity("ASP_Restaurant.Models.MenuPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("menuPositions");
                });

            modelBuilder.Entity("ASP_Restaurant.Models.MenuNamePosition", b =>
                {
                    b.HasOne("ASP_Restaurant.Models.MenuName", "menuName")
                        .WithMany("menuNamePositions")
                        .HasForeignKey("MenuNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP_Restaurant.Models.MenuPosition", "menuPosition")
                        .WithMany("menuNamePositions")
                        .HasForeignKey("MenuPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menuName");

                    b.Navigation("menuPosition");
                });

            modelBuilder.Entity("ASP_Restaurant.Models.MenuName", b =>
                {
                    b.Navigation("menuNamePositions");
                });

            modelBuilder.Entity("ASP_Restaurant.Models.MenuPosition", b =>
                {
                    b.Navigation("menuNamePositions");
                });
#pragma warning restore 612, 618
        }
    }
}
